# Generated by Django 2.0.1 on 2018-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheaterinfo',
            name='wheater',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('rainy', 'Rainy'), ('cloudy', 'Cloudy'), ('misty', 'Misty')], default='sunny', max_length=50),
        ),
    ]
