# Generated by Django 2.0.1 on 2018-03-10 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20180310_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='temperature',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-60), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
