# Generated by Django 2.0.1 on 2018-03-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20180310_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherinfo',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
