# Generated by Django 2.0.1 on 2018-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_weatherinfo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherinfo',
            name='img',
        ),
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
