# Generated by Django 2.0.1 on 2018-03-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_auto_20180312_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cWeather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentWeather', to='weather.WeatherInfo'),
        ),
    ]
