# Generated by Django 2.0.1 on 2018-03-10 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_wheaterinfo_wheater'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tok', 'Tokio'), ('Hel', 'Helsinki'), ('NY', 'New York'), ('Ams', 'Amsterdam'), ('Dub', 'Dubai')], max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('tempature', models.FloatField()),
                ('weather', models.CharField(choices=[('sunny', 'Sunny'), ('rainy', 'Rainy'), ('cloudy', 'Cloudy'), ('misty', 'Misty')], default='sunny', max_length=50)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='WheaterInfo',
        ),
    ]
