# Generated by Django 2.0.1 on 2018-03-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherinfo',
            old_name='tempature',
            new_name='temperature',
        ),
    ]
